### ISSUE TITLE
Calling `Feature::active()` when unauthenticated throws exception

### ISSUE THREAD

**Issue by jordanhavard** [QodeNL/Laravel-Posthog#7]
As the title suggests, calling `Feature::active()` when a user is unauthenticated throws an unhandled excpetion
`method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given`

In the [PosthogFeatureDriver.php#L57](https://github.com/QodeNL/Laravel-Posthog/blob/main/src/Extensions/PosthogFeatureDriver.php#L57) `$scope` should first check for null

**Comment by christianschoenmakers** [comment]
@jordanhavard Thank you! The PR is merged now.
